version: "3.9"

services:
  paperless-ai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PAPERLESS_AI_PORT=3000
      - RAG_SERVICE_URL=http://rag-service:8000
    depends_on:
      - rag-service
    volumes:
      - /data/paperless-ai/data:/app/data
      - /data/paperless-ai/config:/app/data/config
      - /data/paperless-ai/db:/app/data/db
      - /data/paperless-ai/models:/app/data/models
      - /data/paperless-ai/uploads:/app/data/uploads

  rag-service:
    build:
      context: .
      dockerfile: Dockerfile.rag
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - /data/paperless-ai/db:/app/data/db
